package flattrim

import (
	"encoding/json"
	"github.com/stretchr/testify/assert"
	"reflect"
	"testing"
)

func init() {
	flattrimizerInst = NewFlattrimizer(KEEPCASE)
}

func assertMap(t *testing.T, result map[string]interface{}, expected map[string]interface{}) {
	eq := reflect.DeepEqual(result, expected)
	if eq {
		assert.True(t, true)
	} else {
		expectedJSON, _ := json.Marshal(expected)
		resultJSON, _ := json.Marshal(result)
		assert.JSONEqf(t, string(expectedJSON), string(resultJSON), "error message %s", "formatted")
	}
}

func TestFlattrimizer_BuildFlattenKey(t *testing.T) {
	tests := []struct {
		value    string
		expected string
	}{
		{value: "", expected: ""},
		{value: "foo", expected: "foo."},
	}

	for _, test := range tests {
		result := flattrimizerInst.buildFlattenKey(test.value)
		assert.Equal(t, result, test.expected)
	}
}

func TestFlattrimizer_Flatten(t *testing.T) {
	jsonMap := make(map[string]interface{})
	expectedMap := make(map[string]interface{})

	json.Unmarshal([]byte(data), &jsonMap)
	json.Unmarshal([]byte(expectedDataWithPoint), &expectedMap)
	assertMap(t, flattrimizerInst.Flatten(jsonMap), expectedMap)
}

func TestFlattrimizer_FlattenWithBinder(t *testing.T) {
	jsonMap := make(map[string]interface{})
	expectedMap := make(map[string]interface{})

	flattrimizerInst.SetBinder("_")
	json.Unmarshal([]byte(data), &jsonMap)
	json.Unmarshal([]byte(expectedDataWithUnderscore), &expectedMap)
	assertMap(t, flattrimizerInst.Flatten(jsonMap), expectedMap)
}

var (
	flattrimizerInst *flattrimizer
	data             = `{
	"id": 1296269,
	"owner": {
		"login": "octocat",
		"id": 1,
		"avatar_url": "https://github.com/images/error/octocat_happy.gif",
		"gravatar_id": "somehexcode",
		"url": "https://api.github.com/users/octocat",
		"html_url": "https://github.com/octocat",
		"followers_url": "https://api.github.com/users/octocat/followers",
		"following_url": "https://api.github.com/users/octocat/following{/other_user}",
		"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
		"organizations_url": "https://api.github.com/users/octocat/orgs",
		"repos_url": "https://api.github.com/users/octocat/repos",
		"events_url": "https://api.github.com/users/octocat/events{/privacy}",
		"received_events_url": "https://api.github.com/users/octocat/received_events",
		"type": "User",
		"site_admin": false
	},
	"list": [
		"value1",
		3,
		true,
		{
			"value2" : {
				"k1": "v1"
			}
		}
	],
	"name": "Hello-World",
	"full_name": "octocat/Hello-World",
	"description": "This your first repo!",
	"private": false,
	"fork": false,
	"url": "https://api.github.com/repos/octocat/Hello-World",
	"html_url": "https://github.com/octocat/Hello-World",
	"clone_url": "https://github.com/octocat/Hello-World.git",
	"git_url": "git://github.com/octocat/Hello-World.git",
	"ssh_url": "git@github.com:octocat/Hello-World.git",
	"svn_url": "https://svn.github.com/octocat/Hello-World",
	"mirror_url": "git://git.example.com/octocat/Hello-World",
	"homepage": "https://github.com",
	"language": null,
	"forks_count": 9,
	"stargazers_count": 80,
	"watchers_count": 80,
	"size": 108,
	"default_branch": "master",
	"open_issues_count": 0,
	"has_issues": true,
	"has_wiki": true,
	"has_downloads": true,
	"pushed_at": "2011-01-26T19:06:43Z",
	"created_at": "2011-01-26T19:01:12Z",
	"updated_at": "2011-01-26T19:14:43Z",
	"permissions": {
		"admin": false,
		"push": false,
		"pull": true
	},
	"subscribers_count": 42,
	"organization": {
		"login": "octocat",
		"id": 1,
		"avatar_url": "https://github.com/images/error/octocat_happy.gif",
		"gravatar_id": "somehexcode",
		"url": "https://api.github.com/users/octocat",
		"html_url": "https://github.com/octocat",
		"followers_url": "https://api.github.com/users/octocat/followers",
		"following_url": "https://api.github.com/users/octocat/following{/other_user}",
		"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
		"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
		"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
		"organizations_url": "https://api.github.com/users/octocat/orgs",
		"repos_url": "https://api.github.com/users/octocat/repos",
		"events_url": "https://api.github.com/users/octocat/events{/privacy}",
		"received_events_url": "https://api.github.com/users/octocat/received_events",
		"type": "Organization",
		"site_admin": false
	},
	"parent": {
		"id": 1296269,
		"owner": {
			"login": "octocat",
			"id": 1,
			"avatar_url": "https://github.com/images/error/octocat_happy.gif",
			"gravatar_id": "somehexcode",
			"url": "https://api.github.com/users/octocat",
			"html_url": "https://github.com/octocat",
			"followers_url": "https://api.github.com/users/octocat/followers",
			"following_url": "https://api.github.com/users/octocat/following{/other_user}",
			"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
			"organizations_url": "https://api.github.com/users/octocat/orgs",
			"repos_url": "https://api.github.com/users/octocat/repos",
			"events_url": "https://api.github.com/users/octocat/events{/privacy}",
			"received_events_url": "https://api.github.com/users/octocat/received_events",
			"type": "User",
			"site_admin": false
		},
		"name": "Hello-World",
		"full_name": "octocat/Hello-World",
		"description": "This your first repo!",
		"private": false,
		"fork": true,
		"url": "https://api.github.com/repos/octocat/Hello-World",
		"html_url": "https://github.com/octocat/Hello-World",
		"clone_url": "https://github.com/octocat/Hello-World.git",
		"git_url": "git://github.com/octocat/Hello-World.git",
		"ssh_url": "git@github.com:octocat/Hello-World.git",
		"svn_url": "https://svn.github.com/octocat/Hello-World",
		"mirror_url": "git://git.example.com/octocat/Hello-World",
		"homepage": "https://github.com",
		"language": null,
		"forks_count": 9,
		"stargazers_count": 80,
		"watchers_count": 80,
		"size": 108,
		"default_branch": "master",
		"open_issues_count": 0,
		"has_issues": true,
		"has_wiki": true,
		"has_downloads": true,
		"pushed_at": "2011-01-26T19:06:43Z",
		"created_at": "2011-01-26T19:01:12Z",
		"updated_at": "2011-01-26T19:14:43Z",
		"permissions": {
			"admin": false,
			"push": false,
			"pull": true
		}
	},
	"source": {
		"id": 1296269,
		"owner": {
			"login": "octocat",
			"id": 1,
			"avatar_url": "https://github.com/images/error/octocat_happy.gif",
			"gravatar_id": "somehexcode",
			"url": "https://api.github.com/users/octocat",
			"html_url": "https://github.com/octocat",
			"followers_url": "https://api.github.com/users/octocat/followers",
			"following_url": "https://api.github.com/users/octocat/following{/other_user}",
			"gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
			"starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
			"subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
			"organizations_url": "https://api.github.com/users/octocat/orgs",
			"repos_url": "https://api.github.com/users/octocat/repos",
			"events_url": "https://api.github.com/users/octocat/events{/privacy}",
			"received_events_url": "https://api.github.com/users/octocat/received_events",
			"type": "User",
			"site_admin": false
		},
		"name": "Hello-World",
		"full_name": "octocat/Hello-World",
		"description": "This your first repo!",
		"private": false,
		"fork": true,
		"url": "https://api.github.com/repos/octocat/Hello-World",
		"html_url": "https://github.com/octocat/Hello-World",
		"clone_url": "https://github.com/octocat/Hello-World.git",
		"git_url": "git://github.com/octocat/Hello-World.git",
		"ssh_url": "git@github.com:octocat/Hello-World.git",
		"svn_url": "https://svn.github.com/octocat/Hello-World",
		"mirror_url": "git://git.example.com/octocat/Hello-World",
		"homepage": "https://github.com",
		"language": null,
		"forks_count": 9,
		"stargazers_count": 80,
		"watchers_count": 80,
		"size": 108,
		"default_branch": "master",
		"open_issues_count": 0,
		"has_issues": true,
		"has_wiki": true,
		"has_downloads": true,
		"pushed_at": "2011-01-26T19:06:43Z",
		"created_at": "2011-01-26T19:01:12Z",
		"updated_at": "2011-01-26T19:14:43Z",
		"permissions": {
			"admin": false,
			"push": false,
			"pull": true
		}
	}
}`
	expectedDataWithPoint = `{
	"clone_url": "https://github.com/octocat/Hello-World.git",
	"created_at": "2011-01-26T19:01:12Z",
	"default_branch": "master",
	"description": "This your first repo!",
	"fork": false,
	"forks_count": 9,
	"full_name": "octocat/Hello-World",
	"git_url": "git://github.com/octocat/Hello-World.git",
	"has_downloads": true,
	"has_issues": true,
	"has_wiki": true,
	"homepage": "https://github.com",
	"html_url": "https://github.com/octocat/Hello-World",
	"id": 1296269,
	"language": null,
	"mirror_url": "git://git.example.com/octocat/Hello-World",
	"name": "Hello-World",
	"open_issues_count": 0,
	"organization.avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"organization.events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"organization.followers_url": "https://api.github.com/users/octocat/followers",
	"organization.following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"organization.gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"organization.gravatar_id": "somehexcode",
	"organization.html_url": "https://github.com/octocat",
	"organization.id": 1,
	"organization.login": "octocat",
	"organization.organizations_url": "https://api.github.com/users/octocat/orgs",
	"organization.received_events_url": "https://api.github.com/users/octocat/received_events",
	"organization.repos_url": "https://api.github.com/users/octocat/repos",
	"organization.site_admin": false,
	"organization.starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"organization.subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"organization.type": "Organization",
	"organization.url": "https://api.github.com/users/octocat",
	"owner.avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"owner.events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"owner.followers_url": "https://api.github.com/users/octocat/followers",
	"owner.following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"owner.gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"owner.gravatar_id": "somehexcode",
	"owner.html_url": "https://github.com/octocat",
	"owner.id": 1,
	"owner.login": "octocat",
	"owner.organizations_url": "https://api.github.com/users/octocat/orgs",
	"owner.received_events_url": "https://api.github.com/users/octocat/received_events",
	"owner.repos_url": "https://api.github.com/users/octocat/repos",
	"owner.site_admin": false,
	"owner.starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"owner.subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"owner.type": "User",
	"owner.url": "https://api.github.com/users/octocat",
	"list": [
		"value1",
		3,
		true,
		{ "value2.k1":"v1" }
	],
	"parent.clone_url": "https://github.com/octocat/Hello-World.git",
	"parent.created_at": "2011-01-26T19:01:12Z",
	"parent.default_branch": "master",
	"parent.description": "This your first repo!",
	"parent.fork": true,
	"parent.forks_count": 9,
	"parent.full_name": "octocat/Hello-World",
	"parent.git_url": "git://github.com/octocat/Hello-World.git",
	"parent.has_downloads": true,
	"parent.has_issues": true,
	"parent.has_wiki": true,
	"parent.homepage": "https://github.com",
	"parent.html_url": "https://github.com/octocat/Hello-World",
	"parent.id": 1296269,
	"parent.language": null,
	"parent.mirror_url": "git://git.example.com/octocat/Hello-World",
	"parent.name": "Hello-World",
	"parent.open_issues_count": 0,
	"parent.owner.avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"parent.owner.events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"parent.owner.followers_url": "https://api.github.com/users/octocat/followers",
	"parent.owner.following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"parent.owner.gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"parent.owner.gravatar_id": "somehexcode",
	"parent.owner.html_url": "https://github.com/octocat",
	"parent.owner.id": 1,
	"parent.owner.login": "octocat",
	"parent.owner.organizations_url": "https://api.github.com/users/octocat/orgs",
	"parent.owner.received_events_url": "https://api.github.com/users/octocat/received_events",
	"parent.owner.repos_url": "https://api.github.com/users/octocat/repos",
	"parent.owner.site_admin": false,
	"parent.owner.starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"parent.owner.subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"parent.owner.type": "User",
	"parent.owner.url": "https://api.github.com/users/octocat",
	"parent.permissions.admin": false,
	"parent.permissions.pull": true,
	"parent.permissions.push": false,
	"parent.private": false,
	"parent.pushed_at": "2011-01-26T19:06:43Z",
	"parent.size": 108,
	"parent.ssh_url": "git@github.com:octocat/Hello-World.git",
	"parent.stargazers_count": 80,
	"parent.svn_url": "https://svn.github.com/octocat/Hello-World",
	"parent.updated_at": "2011-01-26T19:14:43Z",
	"parent.url": "https://api.github.com/repos/octocat/Hello-World",
	"parent.watchers_count": 80,
	"permissions.admin": false,
	"permissions.pull": true,
	"permissions.push": false,
	"private": false,
	"pushed_at": "2011-01-26T19:06:43Z",
	"size": 108,
	"source.clone_url": "https://github.com/octocat/Hello-World.git",
	"source.created_at": "2011-01-26T19:01:12Z",
	"source.default_branch": "master",
	"source.description": "This your first repo!",
	"source.fork": true,
	"source.forks_count": 9,
	"source.full_name": "octocat/Hello-World",
	"source.git_url": "git://github.com/octocat/Hello-World.git",
	"source.has_downloads": true,
	"source.has_issues": true,
	"source.has_wiki": true,
	"source.homepage": "https://github.com",
	"source.html_url": "https://github.com/octocat/Hello-World",
	"source.id": 1296269,
	"source.language": null,
	"source.mirror_url": "git://git.example.com/octocat/Hello-World",
	"source.name": "Hello-World",
	"source.open_issues_count": 0,
	"source.owner.avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"source.owner.events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"source.owner.followers_url": "https://api.github.com/users/octocat/followers",
	"source.owner.following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"source.owner.gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"source.owner.gravatar_id": "somehexcode",
	"source.owner.html_url": "https://github.com/octocat",
	"source.owner.id": 1,
	"source.owner.login": "octocat",
	"source.owner.organizations_url": "https://api.github.com/users/octocat/orgs",
	"source.owner.received_events_url": "https://api.github.com/users/octocat/received_events",
	"source.owner.repos_url": "https://api.github.com/users/octocat/repos",
	"source.owner.site_admin": false,
	"source.owner.starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"source.owner.subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"source.owner.type": "User",
	"source.owner.url": "https://api.github.com/users/octocat",
	"source.permissions.admin": false,
	"source.permissions.pull": true,
	"source.permissions.push": false,
	"source.private": false,
	"source.pushed_at": "2011-01-26T19:06:43Z",
	"source.size": 108,
	"source.ssh_url": "git@github.com:octocat/Hello-World.git",
	"source.stargazers_count": 80,
	"source.svn_url": "https://svn.github.com/octocat/Hello-World",
	"source.updated_at": "2011-01-26T19:14:43Z",
	"source.url": "https://api.github.com/repos/octocat/Hello-World",
	"source.watchers_count": 80,
	"ssh_url": "git@github.com:octocat/Hello-World.git",
	"stargazers_count": 80,
	"subscribers_count": 42,
	"svn_url": "https://svn.github.com/octocat/Hello-World",
	"updated_at": "2011-01-26T19:14:43Z",
	"url": "https://api.github.com/repos/octocat/Hello-World",
	"watchers_count": 80
}`
	expectedDataWithUnderscore = `{
	"clone_url": "https://github.com/octocat/Hello-World.git",
	"created_at": "2011-01-26T19:01:12Z",
	"default_branch": "master",
	"description": "This your first repo!",
	"fork": false,
	"forks_count": 9,
	"full_name": "octocat/Hello-World",
	"git_url": "git://github.com/octocat/Hello-World.git",
	"has_downloads": true,
	"has_issues": true,
	"has_wiki": true,
	"homepage": "https://github.com",
	"html_url": "https://github.com/octocat/Hello-World",
	"id": 1296269,
	"language": null,
	"mirror_url": "git://git.example.com/octocat/Hello-World",
	"name": "Hello-World",
	"open_issues_count": 0,
	"organization_avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"organization_events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"organization_followers_url": "https://api.github.com/users/octocat/followers",
	"organization_following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"organization_gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"organization_gravatar_id": "somehexcode",
	"organization_html_url": "https://github.com/octocat",
	"organization_id": 1,
	"organization_login": "octocat",
	"organization_organizations_url": "https://api.github.com/users/octocat/orgs",
	"organization_received_events_url": "https://api.github.com/users/octocat/received_events",
	"organization_repos_url": "https://api.github.com/users/octocat/repos",
	"organization_site_admin": false,
	"organization_starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"organization_subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"organization_type": "Organization",
	"organization_url": "https://api.github.com/users/octocat",
	"owner_avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"owner_events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"owner_followers_url": "https://api.github.com/users/octocat/followers",
	"owner_following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"owner_gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"owner_gravatar_id": "somehexcode",
	"owner_html_url": "https://github.com/octocat",
	"owner_id": 1,
	"owner_login": "octocat",
	"owner_organizations_url": "https://api.github.com/users/octocat/orgs",
	"owner_received_events_url": "https://api.github.com/users/octocat/received_events",
	"owner_repos_url": "https://api.github.com/users/octocat/repos",
	"owner_site_admin": false,
	"owner_starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"owner_subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"owner_type": "User",
	"owner_url": "https://api.github.com/users/octocat",
	"list": [
		"value1",
		3,
		true,
		{ "value2_k1":"v1" }
	],
	"parent_clone_url": "https://github.com/octocat/Hello-World.git",
	"parent_created_at": "2011-01-26T19:01:12Z",
	"parent_default_branch": "master",
	"parent_description": "This your first repo!",
	"parent_fork": true,
	"parent_forks_count": 9,
	"parent_full_name": "octocat/Hello-World",
	"parent_git_url": "git://github.com/octocat/Hello-World.git",
	"parent_has_downloads": true,
	"parent_has_issues": true,
	"parent_has_wiki": true,
	"parent_homepage": "https://github.com",
	"parent_html_url": "https://github.com/octocat/Hello-World",
	"parent_id": 1296269,
	"parent_language": null,
	"parent_mirror_url": "git://git.example.com/octocat/Hello-World",
	"parent_name": "Hello-World",
	"parent_open_issues_count": 0,
	"parent_owner_avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"parent_owner_events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"parent_owner_followers_url": "https://api.github.com/users/octocat/followers",
	"parent_owner_following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"parent_owner_gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"parent_owner_gravatar_id": "somehexcode",
	"parent_owner_html_url": "https://github.com/octocat",
	"parent_owner_id": 1,
	"parent_owner_login": "octocat",
	"parent_owner_organizations_url": "https://api.github.com/users/octocat/orgs",
	"parent_owner_received_events_url": "https://api.github.com/users/octocat/received_events",
	"parent_owner_repos_url": "https://api.github.com/users/octocat/repos",
	"parent_owner_site_admin": false,
	"parent_owner_starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"parent_owner_subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"parent_owner_type": "User",
	"parent_owner_url": "https://api.github.com/users/octocat",
	"parent_permissions_admin": false,
	"parent_permissions_pull": true,
	"parent_permissions_push": false,
	"parent_private": false,
	"parent_pushed_at": "2011-01-26T19:06:43Z",
	"parent_size": 108,
	"parent_ssh_url": "git@github.com:octocat/Hello-World.git",
	"parent_stargazers_count": 80,
	"parent_svn_url": "https://svn.github.com/octocat/Hello-World",
	"parent_updated_at": "2011-01-26T19:14:43Z",
	"parent_url": "https://api.github.com/repos/octocat/Hello-World",
	"parent_watchers_count": 80,
	"permissions_admin": false,
	"permissions_pull": true,
	"permissions_push": false,
	"private": false,
	"pushed_at": "2011-01-26T19:06:43Z",
	"size": 108,
	"source_clone_url": "https://github.com/octocat/Hello-World.git",
	"source_created_at": "2011-01-26T19:01:12Z",
	"source_default_branch": "master",
	"source_description": "This your first repo!",
	"source_fork": true,
	"source_forks_count": 9,
	"source_full_name": "octocat/Hello-World",
	"source_git_url": "git://github.com/octocat/Hello-World.git",
	"source_has_downloads": true,
	"source_has_issues": true,
	"source_has_wiki": true,
	"source_homepage": "https://github.com",
	"source_html_url": "https://github.com/octocat/Hello-World",
	"source_id": 1296269,
	"source_language": null,
	"source_mirror_url": "git://git.example.com/octocat/Hello-World",
	"source_name": "Hello-World",
	"source_open_issues_count": 0,
	"source_owner_avatar_url": "https://github.com/images/error/octocat_happy.gif",
	"source_owner_events_url": "https://api.github.com/users/octocat/events{/privacy}",
	"source_owner_followers_url": "https://api.github.com/users/octocat/followers",
	"source_owner_following_url": "https://api.github.com/users/octocat/following{/other_user}",
	"source_owner_gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
	"source_owner_gravatar_id": "somehexcode",
	"source_owner_html_url": "https://github.com/octocat",
	"source_owner_id": 1,
	"source_owner_login": "octocat",
	"source_owner_organizations_url": "https://api.github.com/users/octocat/orgs",
	"source_owner_received_events_url": "https://api.github.com/users/octocat/received_events",
	"source_owner_repos_url": "https://api.github.com/users/octocat/repos",
	"source_owner_site_admin": false,
	"source_owner_starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
	"source_owner_subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
	"source_owner_type": "User",
	"source_owner_url": "https://api.github.com/users/octocat",
	"source_permissions_admin": false,
	"source_permissions_pull": true,
	"source_permissions_push": false,
	"source_private": false,
	"source_pushed_at": "2011-01-26T19:06:43Z",
	"source_size": 108,
	"source_ssh_url": "git@github.com:octocat/Hello-World.git",
	"source_stargazers_count": 80,
	"source_svn_url": "https://svn.github.com/octocat/Hello-World",
	"source_updated_at": "2011-01-26T19:14:43Z",
	"source_url": "https://api.github.com/repos/octocat/Hello-World",
	"source_watchers_count": 80,
	"ssh_url": "git@github.com:octocat/Hello-World.git",
	"stargazers_count": 80,
	"subscribers_count": 42,
	"svn_url": "https://svn.github.com/octocat/Hello-World",
	"updated_at": "2011-01-26T19:14:43Z",
	"url": "https://api.github.com/repos/octocat/Hello-World",
	"watchers_count": 80
}`
)
